# Generated by Django 5.1 on 2024-08-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_author_biography_remove_book_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
    ]
